# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
import sys
from typing import TypedDict

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langgraph.graph import END, StateGraph

INDEX_PATH = "faiss_index"

TEST_QUERIES = [
    "What is trunk-based development and why do teams adopt it?",
    "How does technical debt accumulate and how should teams address it?",
    "What is the difference between microservices and a monolith?",
    "What are the current interest rates set by the Federal Reserve?",
]


class GraphState(TypedDict, total=False):
    question: str
    retrieved_docs: list[Document]
    relevant_docs: list[Document]
    grading_trace: list[str]
    answer: str


def normalize_grade(raw_text: str) -> str:
    value = raw_text.strip().lower()

    if "irrelevant" in value:
        return "irrelevant"
    if "relevant" in value:
        return "relevant"
    return "irrelevant"


def unique_titles(docs: list[Document]) -> list[str]:
    seen = set()
    titles = []

    for doc in docs:
        title = doc.metadata["doc_title"]
        if title not in seen:
            seen.add(title)
            titles.append(title)

    return titles


def build_graph(vectorstore: FAISS, llm: ChatOpenAI):
    def retriever_node(state: GraphState) -> GraphState:
        question = state["question"]
        retrieved_docs = vectorstore.similarity_search(question, k=4)
        return {"retrieved_docs": retrieved_docs}

    def grader_node(state: GraphState) -> GraphState:
        question = state["question"]
        retrieved_docs = state.get("retrieved_docs", [])
        relevant_docs: list[Document] = []
        grading_trace: list[str] = []

        for doc in retrieved_docs:
            prompt = (
                f"Is the following text relevant to answering this question: "
                f"{question}? Reply with only: relevant or irrelevant.\n\n"
                f"Text:\n{doc.page_content}"
            )

            result = llm.invoke(prompt)
            decision = normalize_grade(result.content)

            trace_line = (
                f"[GRADE] title='{doc.metadata['doc_title']}', "
                f"chunk={doc.metadata['chunk_index']}, decision={decision}"
            )
            print(trace_line)
            grading_trace.append(trace_line)

            if decision == "relevant":
                relevant_docs.append(doc)

        return {
            "relevant_docs": relevant_docs,
            "grading_trace": grading_trace,
        }

    def generator_node(state: GraphState) -> GraphState:
        question = state["question"]
        relevant_docs = state.get("relevant_docs", [])

        if len(relevant_docs) == 0:
            return {
                "answer": (
                    "Insufficient information in the knowledge base "
                    "to answer this question."
                )
            }

        context = "\n\n".join(
            [
                (
                    f"Title: {doc.metadata['doc_title']}\n"
                    f"Chunk Index: {doc.metadata['chunk_index']}\n"
                    f"Text: {doc.page_content}"
                )
                for doc in relevant_docs
            ]
        )

        answer_prompt = f"""
Answer the question using ONLY the context below.

Question:
{question}

Context:
{context}

Rules:
- Use only the supplied context.
- Do not add outside knowledge.
- Answer in 2-4 sentences.
- Keep the answer factual and concise.
""".strip()

        answer_text = llm.invoke(answer_prompt).content.strip()
        titles = unique_titles(relevant_docs)
        sources_line = "Sources: " + ", ".join(f"[{title}]" for title in titles)

        if len(relevant_docs) == 1:
            final_answer = (
                "Note: only one source available — answer may be incomplete.\n\n"
                f"{answer_text}\n\n"
                f"{sources_line}"
            )
        else:
            final_answer = f"{answer_text}\n\n{sources_line}"

        return {"answer": final_answer}

    graph = StateGraph(GraphState)
    graph.add_node("retriever", retriever_node)
    graph.add_node("grader", grader_node)
    graph.add_node("generator", generator_node)

    graph.set_entry_point("retriever")
    graph.add_edge("retriever", "grader")
    graph.add_edge("grader", "generator")
    graph.add_edge("generator", END)

    app = graph.compile()
    from IPython.display import Image, display

    png_bytes = app.get_graph().draw_mermaid_png()

    with open("logic.png", "wb") as f:
        f.write(png_bytes)

    print("Graph image saved as langgraph.png")

    return app


def load_app():
    load_dotenv()

    if not os.getenv("OPENAI_API_KEY"):
        raise EnvironmentError("OPENAI_API_KEY is not set.")

    embeddings = OpenAIEmbeddings(model="text-embedding-3-small", base_url='https://us.api.openai.com/v1')
    vectorstore = FAISS.load_local(
        INDEX_PATH,
        embeddings,
        allow_dangerous_deserialization=True,
    )
    llm = ChatOpenAI(model="gpt-4.1", temperature=0, base_url='https://us.api.openai.com/v1')
    return build_graph(vectorstore, llm)


def run_query(app, query: str) -> None:
    print("\n" + "=" * 80)
    print(f"QUESTION: {query}")
    print("=" * 80)

    result = app.invoke({"question": query})

    print("\nANSWER:")
    print(result["answer"])


def main() -> None:
    app = load_app()

    print("Internal Knowledge Base Assistant")
    print("Type 'exit' to quit.\n")

    while True:
        query = input("Enter your question: ").strip()

        if query.lower() in {"exit", "quit"}:
            print("Goodbye!")
            break

        if not query:
            print("Please enter a valid question.\n")
            continue

        print("\n" + "=" * 80)
        print(f"QUESTION: {query}")
        print("=" * 80)

        result = app.invoke({"question": query})

        print("\nANSWER:")
        print(result["answer"])
        print("\n")


if __name__ == "__main__":
    main()
