# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from pathlib import Path
from typing import Dict, List, Set

from dotenv import load_dotenv
import autogen

FEATURE_REQUEST = (
    "Add real-time task status notifications so that team members are "
    "instantly alerted via the app when any of their assigned tasks are updated."
)

DEPLOYMENT_SENTINEL = (
    "DEPLOYMENT_COMPLETE: Task Notifications v1.0 deployed to staging"
)

REPORT_SECTIONS = [
    "# Executive Summary",
    "# Technical Design",
    "# Test Coverage",
    "# Deployment Configuration",
    "# Open Questions",
]

OUTPUT_DIR = Path("artifacts")
TRANSCRIPT_PATH = OUTPUT_DIR / "transcript.txt"
REPORT_PATH = OUTPUT_DIR / "delivery_report.md"


def is_termination_msg(message) -> bool:
    if isinstance(message, dict):
        content = message.get("content", "") or ""
    else:
        content = str(message)
    return DEPLOYMENT_SENTINEL in content


def build_llm_config() -> Dict:
    api_key = os.getenv("OPENAI_API_KEY")
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

    if not api_key:
        raise ValueError("OPENAI_API_KEY is required.")

    return {
        "config_list": [{"model": model, "api_key": api_key}],
        "temperature": 0.2,
        "timeout": 120,
    }


def build_agents(llm_config: Dict) -> Dict[str, autogen.ConversableAgent]:
    name_rule = (
        "When building on another team member's input, reference their name explicitly."
    )

    product_owner = autogen.AssistantAgent(
        name="ProductOwner",
        llm_config=llm_config,
        is_termination_msg=is_termination_msg,
        system_message=(
            "You are ProductOwner.\n"
            "Your job is to write 3-5 acceptance criteria in Given/When/Then format.\n"
            "Prioritise the criteria by business value.\n"
            "Challenge TechLead if the design misses or weakens any acceptance criterion.\n"
            "Keep your response concise and numbered.\n"
            f"{name_rule}"
        ),
    )

    tech_lead = autogen.AssistantAgent(
        name="TechLead",
        llm_config=llm_config,
        is_termination_msg=is_termination_msg,
        system_message=(
            "You are TechLead.\n"
            "Propose the technical architecture for the feature.\n"
            "Choose exactly one stack approach from: WebSockets, SSE, polling.\n"
            "Explain required components and data flow from task update to notification.\n"
            "Assign implementation work to Developer.\n"
            "After Developer responds, review the output and explicitly approve or request changes.\n"
            "Ensure the design satisfies ProductOwner's acceptance criteria.\n"
            f"{name_rule}"
        ),
    )

    developer = autogen.AssistantAgent(
        name="Developer",
        llm_config=llm_config,
        is_termination_msg=is_termination_msg,
        system_message=(
            "You are Developer.\n"
            "Respond to TechLead's design.\n"
            "Write key function signatures and pseudocode for these core components:\n"
            "1) WebSocket connection handler\n"
            "2) Event publisher triggered on task update\n"
            "3) Client subscription manager\n"
            "After TechLead reviews, respond to the review if needed.\n"
            "Use concise Python-like pseudocode.\n"
            f"{name_rule}"
        ),
    )

    tester = autogen.AssistantAgent(
        name="Tester",
        llm_config=llm_config,
        is_termination_msg=is_termination_msg,
        system_message=(
            "You are Tester.\n"
            "Define exactly 5 test cases aligned to the architecture proposed by TechLead "
            "and the implementation proposed by Developer.\n"
            "Include these five cases exactly:\n"
            "1) happy path — user receives notification within 500ms\n"
            "2) concurrent connections — 100 users connected simultaneously\n"
            "3) reconnection — client recovers after disconnect\n"
            "4) authentication — unauthenticated users cannot subscribe\n"
            "5) message format validation — notification contains correct task_id, "
            "status, and timestamp\n"
            "Format each case with objective, steps, and expected result.\n"
            f"{name_rule}"
        ),
    )

    devops = autogen.AssistantAgent(
        name="DevOps",
        llm_config=llm_config,
        is_termination_msg=is_termination_msg,
        system_message=(
            "You are DevOps.\n"
            "Describe deployment configuration for staging: Docker setup, port exposure, "
            "environment variables, and health check endpoint.\n"
            "Wait until ProductOwner, TechLead, Developer, and Tester have completed their work.\n"
            "When all work is complete, output exactly this final line and nothing after it:\n"
            f"{DEPLOYMENT_SENTINEL}\n"
            f"{name_rule}"
        ),
    )

    documentation_writer = autogen.AssistantAgent(
        name="DocumentationWriter",
        llm_config=llm_config,
        system_message=(
            "You are DocumentationWriter.\n"
            "You do not participate in the group chat.\n"
            "After receiving the full transcript, produce markdown for delivery_report.md.\n"
            "Use exactly these 5 sections and no others:\n"
            "# Executive Summary\n"
            "# Technical Design\n"
            "# Test Coverage\n"
            "# Deployment Configuration\n"
            "# Open Questions\n"
            "Reflect the actual transcript only. Do not invent missing decisions.\n"
            f"{name_rule}"
        ),
    )

    delivery_manager = autogen.UserProxyAgent(
        name="DeliveryManager",
        human_input_mode="NEVER",
        code_execution_config=False,
        is_termination_msg=is_termination_msg,
    )

    report_requester = autogen.UserProxyAgent(
        name="ReportRequester",
        human_input_mode="NEVER",
        code_execution_config=False,
    )

    return {
        "ProductOwner": product_owner,
        "TechLead": tech_lead,
        "Developer": developer,
        "Tester": tester,
        "DevOps": devops,
        "DocumentationWriter": documentation_writer,
        "DeliveryManager": delivery_manager,
        "ReportRequester": report_requester,
    }


def build_groupchat(agents: Dict[str, autogen.ConversableAgent], llm_config: Dict):
    group_agents = [
        agents["ProductOwner"],
        agents["TechLead"],
        agents["Developer"],
        agents["Tester"],
        agents["DevOps"],
    ]

    groupchat = autogen.GroupChat(
        agents=group_agents,
        messages=[],
        max_round=15,
        speaker_selection_method="auto",
    )

    manager = autogen.GroupChatManager(
        name="GroupChatManager",
        groupchat=groupchat,
        llm_config=llm_config,
    )
    return groupchat, manager


def kickoff_message() -> str:
    return f"""
Feature request:
{FEATURE_REQUEST}

Run this as a collaborative software delivery simulation.

Required flow:
1. ProductOwner goes first with prioritised acceptance criteria.
2. TechLead proposes architecture, chooses one stack from WebSockets/SSE/polling,
   explains data flow, and assigns work to Developer.
3. Developer writes key function signatures and pseudocode for:
   - WebSocket connection handler
   - Event publisher triggered on task update
   - Client subscription manager
4. Tester writes exactly 5 test cases matching the agreed design.
5. TechLead reviews Developer's output and explicitly approves or requests changes.
6. DevOps writes staging deployment configuration.
7. When all prior work is complete, DevOps must output exactly:
{DEPLOYMENT_SENTINEL}

Rules:
- Every role must contribute meaningfully.
- When building on prior input, reference teammates by name explicitly.
- Keep outputs structured and specific.
""".strip()


def render_transcript(messages: List[Dict]) -> str:
    lines = []
    for index, message in enumerate(messages, start=1):
        speaker = message.get("name") or message.get("role", "unknown")
        content = (message.get("content") or "").strip()
        lines.append(f"[{index}] {speaker}\n{content}\n")
    return "\n".join(lines).strip() + "\n"


def assert_distinct_system_messages(agents: Dict[str, autogen.ConversableAgent]) -> None:
    system_messages = [
        agents["ProductOwner"].system_message,
        agents["TechLead"].system_message,
        agents["Developer"].system_message,
        agents["Tester"].system_message,
        agents["DevOps"].system_message,
        agents["DocumentationWriter"].system_message,
    ]
    if len(system_messages) != len(set(system_messages)):
        raise AssertionError("Agent system messages must be distinct.")


def assert_groupchat_completion(messages: List[Dict]) -> None:
    speakers: Set[str] = {
        (message.get("name") or message.get("role", ""))
        for message in messages
    }
    required = {"ProductOwner", "TechLead", "Developer", "Tester", "DevOps"}
    missing = required - speakers
    if missing:
        raise AssertionError(f"Missing group chat contributions from: {sorted(missing)}")

    transcript = render_transcript(messages)
    if DEPLOYMENT_SENTINEL not in transcript:
        raise AssertionError("Deployment termination message was not produced.")


def generate_report(
    documentation_writer: autogen.ConversableAgent,
    report_requester: autogen.ConversableAgent,
    transcript_text: str,
) -> str:
    prompt = f"""
Write delivery_report.md from the transcript below.

Requirements:
- Output markdown only.
- Include exactly these sections:
# Executive Summary
# Technical Design
# Test Coverage
# Deployment Configuration
# Open Questions
- Technical Design must include architecture decisions and rationale.
- Test Coverage must reflect all 5 test cases from Tester.
- Open Questions must include only unresolved items from the transcript.

Transcript:
{transcript_text}
""".strip()

    report_requester.initiate_chat(documentation_writer, message=prompt)
    report = documentation_writer.last_message(report_requester)["content"].strip()

    missing_sections = [section for section in REPORT_SECTIONS if section not in report]
    if missing_sections:
        raise AssertionError(f"Report missing sections: {missing_sections}")

    return report + "\n"


def main() -> None:
    load_dotenv()
    OUTPUT_DIR.mkdir(exist_ok=True)

    llm_config = build_llm_config()
    agents = build_agents(llm_config)

    assert_distinct_system_messages(agents)

    groupchat, manager = build_groupchat(agents, llm_config)

    agents["DeliveryManager"].initiate_chat(manager, message=kickoff_message())

    transcript_text = render_transcript(groupchat.messages)
    assert_groupchat_completion(groupchat.messages)
    TRANSCRIPT_PATH.write_text(transcript_text, encoding="utf-8")

    report_text = generate_report(
        documentation_writer=agents["DocumentationWriter"],
        report_requester=agents["ReportRequester"],
        transcript_text=transcript_text,
    )
    REPORT_PATH.write_text(report_text, encoding="utf-8")

    print("Simulation complete.")
    print(f"Transcript saved to: {TRANSCRIPT_PATH}")
    print(f"Report saved to: {REPORT_PATH}")


if __name__ == "__main__":
    main()
