# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
import sqlite3

DB_PATH = "project_analytics.db"


def recreate_database() -> None:
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.executescript(
        """
        CREATE TABLE projects (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            status TEXT CHECK(
                status IN ('planning', 'active', 'on_hold', 'completed', 'cancelled')
            ),
            priority TEXT CHECK(priority IN ('low', 'medium', 'high', 'critical')),
            start_date DATE,
            due_date DATE,
            team_lead TEXT,
            budget_usd INTEGER
        );

        CREATE TABLE tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_id INTEGER REFERENCES projects(id),
            title TEXT NOT NULL,
            status TEXT CHECK(
                status IN ('todo', 'in_progress', 'review', 'done', 'blocked')
            ),
            assignee TEXT,
            story_points INTEGER,
            due_date DATE
        );

        CREATE TABLE team_members (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            role TEXT,
            department TEXT,
            email TEXT UNIQUE,
            hourly_rate INTEGER,
            skills TEXT
        );

        CREATE TABLE incidents (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            severity TEXT CHECK(severity IN ('critical', 'high', 'medium', 'low')),
            project_id INTEGER REFERENCES projects(id),
            reporter TEXT,
            assigned_to TEXT,
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """
    )

    projects = [
        (
            "Apollo Revamp",
            "active",
            "high",
            "2026-01-15",
            "2026-08-30",
            "Alice Johnson",
            250000,
        ),
        (
            "Neptune Migration",
            "planning",
            "critical",
            "2026-03-01",
            "2026-11-15",
            "Bob Smith",
            400000,
        ),
        (
            "Orion Support",
            "on_hold",
            "medium",
            "2025-12-10",
            "2026-07-20",
            "Carol Lee",
            120000,
        ),
    ]

    team_members = [
        (
            "Alice Johnson",
            "Engineering Manager",
            "Engineering",
            "alice.johnson@example.com",
            120,
            "python,sql,architecture",
        ),
        (
            "Bob Smith",
            "Backend Engineer",
            "Engineering",
            "bob.smith@example.com",
            95,
            "python,apis,sqlite",
        ),
        (
            "Carol Lee",
            "Frontend Engineer",
            "Engineering",
            "carol.lee@example.com",
            90,
            "react,ui,testing",
        ),
        (
            "David Kim",
            "Data Analyst",
            "Analytics",
            "david.kim@example.com",
            85,
            "sql,reporting,dashboards",
        ),
    ]

    tasks = [
        (1, "Design API contracts", "done", "Alice Johnson", 5, "2026-02-01"),
        (1, "Build auth service", "blocked", "Bob Smith", 8, "2026-04-10"),
        (1, "Frontend integration", "in_progress", "Carol Lee", 5, "2026-04-22"),
        (2, "Assess legacy systems", "review", "David Kim", 3, "2026-03-18"),
        (2, "Plan cutover", "todo", "Alice Johnson", 5, "2026-05-01"),
        (2, "Data migration scripts", "blocked", "Bob Smith", 8, "2026-06-15"),
        (3, "Incident triage playbook", "done", "Carol Lee", 2, "2026-01-30"),
        (3, "Monitoring dashboard", "in_progress", "David Kim", 5, "2026-02-28"),
    ]

    incidents = [
        (
            "Production outage",
            "critical",
            1,
            "Alice Johnson",
            "Bob Smith",
            "Authentication service unavailable for all users.",
        ),
        (
            "Migration risk identified",
            "high",
            2,
            "David Kim",
            "Alice Johnson",
            "Legacy data mapping issue may delay cutover.",
        ),
        (
            "Dashboard color mismatch",
            "low",
            3,
            "Carol Lee",
            "David Kim",
            "Minor UI inconsistency in monitoring dashboard.",
        ),
    ]

    cursor.executemany(
        """
        INSERT INTO projects (
            name, status, priority, start_date, due_date, team_lead, budget_usd
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        projects,
    )

    cursor.executemany(
        """
        INSERT INTO team_members (
            name, role, department, email, hourly_rate, skills
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        team_members,
    )

    cursor.executemany(
        """
        INSERT INTO tasks (
            project_id, title, status, assignee, story_points, due_date
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        tasks,
    )

    cursor.executemany(
        """
        INSERT INTO incidents (
            title, severity, project_id, reporter, assigned_to, description
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        incidents,
    )

    conn.commit()

    print(f"Database recreated at: {DB_PATH}")
    print("Seeded:")
    print("  - 3 projects")
    print("  - 8 tasks")
    print("  - 4 team members")
    print("  - 3 incidents")

    print("\nManual verification queries:")
    print("  1. SELECT COUNT(*) FROM tasks;")
    print("  2. SELECT severity, COUNT(*) FROM incidents GROUP BY severity;")

    conn.close()


if __name__ == "__main__":
    recreate_database()
