# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: writer_agent.py

import logging
import os
from typing import Any, Dict, TypedDict
from uuid import uuid4

import httpx
from fastapi import FastAPI, HTTPException
from langgraph.graph import END, START, StateGraph
from openai import AsyncOpenAI
from pydantic import BaseModel


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

app = FastAPI(title="WriterAgent", version="1.0")
client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

AGENT_CARD_URL = os.getenv(
    "RESEARCH_AGENT_CARD_URL",
    "http://localhost:8001/.well-known/agent.json",
)


class WriterState(TypedDict, total=False):
    topic: str
    agent_card: Dict[str, Any]
    task_id: str
    research_result: str
    article: str


class WriteRequest(BaseModel):
    topic: str


class WriteResponse(BaseModel):
    topic: str
    agent_name: str
    research_result: str
    article: str


async def discovery_node(state: WriterState) -> WriterState:
    async with httpx.AsyncClient(timeout=30.0) as http_client:
        response = await http_client.get(AGENT_CARD_URL)
        response.raise_for_status()
        agent_card = response.json()

    skill_names = ", ".join(skill["name"] for skill in agent_card.get("skills", []))
    logging.info(
        f"Agent discovered: {agent_card['name']} v{agent_card['version']} — Skills: {skill_names}"
    )
    return {"agent_card": agent_card}


async def delegation_node(state: WriterState) -> WriterState:
    agent_card = state["agent_card"]
    task_id = str(uuid4())
    base_url = agent_card["url"]

    payload = {
        "id": task_id,
        "message": {
            "role": "user",
            "content": state["topic"],
        },
    }

    async with httpx.AsyncClient(timeout=60.0) as http_client:
        send_response = await http_client.post(f"{base_url}/tasks/send", json=payload)
        send_response.raise_for_status()

        result_response = await http_client.get(f"{base_url}/tasks/{task_id}")
        result_response.raise_for_status()
        task_result = result_response.json()

    research_result = task_result["output"]
    logging.info(
        f"A2A task {task_id} completed. Research received ({len(research_result)} characters)."
    )

    return {
        "task_id": task_id,
        "research_result": research_result,
    }


def build_writer_prompt(topic: str, research_result: str) -> str:
    return f"""
You are a writing agent.

Using only the research below, write an approximately 300-word brief on the topic.
The brief must be grounded in the supplied research and must not become generic.

Structure requirements:
- Introduction: 60-80 words
- Main Body: 2 paragraphs
- Each main body paragraph must reference at least 1 fact from the research
- Conclusion: 60-80 words

Style requirements:
- Use plain English
- Keep it informative and coherent
- Mention facts/trends/challenge from the research explicitly
- Do not use bullet points
- Add section headings: Introduction, Main Body, Conclusion

Topic:
{topic}

Research:
{research_result}
""".strip()


async def writer_node(state: WriterState) -> WriterState:
    if not os.getenv("OPENAI_API_KEY"):
        raise HTTPException(status_code=500, detail="OPENAI_API_KEY is not set.")

    response = await client.responses.create(
        model="gpt-4.1",
        input=build_writer_prompt(state["topic"], state["research_result"]),
    )

    return {"article": response.output_text.strip()}


graph_builder = StateGraph(WriterState)
graph_builder.add_node("discovery_node", discovery_node)
graph_builder.add_node("delegation_node", delegation_node)
graph_builder.add_node("writer_node", writer_node)

graph_builder.add_edge(START, "discovery_node")
graph_builder.add_edge("discovery_node", "delegation_node")
graph_builder.add_edge("delegation_node", "writer_node")
graph_builder.add_edge("writer_node", END)

graph = graph_builder.compile()


@app.post("/write", response_model=WriteResponse)
async def write_brief(request: WriteRequest):
    try:
        result = await graph.ainvoke({"topic": request.topic})
        return WriteResponse(
            topic=request.topic,
            agent_name=result["agent_card"]["name"],
            research_result=result["research_result"],
            article=result["article"],
        )
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"A2A communication failed: {exc}") from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
