# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app.py
import os
from typing import List, Literal, TypedDict

from dotenv import load_dotenv
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field

load_dotenv()

MAX_TOOL_CALLS = 6


class AgentState(TypedDict):
    user_question: str
    thought: str
    action: str
    action_input: str
    observation: str
    observations: List[str]
    tool_calls: int
    final_answer: str
    used_tools: List[str]


class AgentDecision(BaseModel):
    thought: str = Field(description="What the agent is thinking")
    action: Literal[
        "story_estimator",
        "tech_stack_advisor",
        "doc_summariser",
        "final_answer",
    ] = Field(description="Next action")
    action_input: str = Field(default="", description="Input for the tool")
    final_answer: str = Field(default="", description="Answer for user if done")


llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    api_key=os.getenv("OPENAI_API_KEY"),
)

planner = llm.with_structured_output(AgentDecision)


@tool
def story_estimator(description: str) -> str:
    """Estimate story points for a feature description."""
    text = description.lower()

    if "oauth" in text or "login" in text or "auth" in text:
        return (
            "5 points — requires authentication flow and session handling. "
            "No major new infrastructure appears necessary."
        )

    if "csv" in text or "export" in text:
        return (
            "3 points — requires backend export logic and dashboard UI changes. "
            "The work is moderate and stays inside the existing product area."
        )

    if "real-time" in text or "notification" in text:
        return (
            "8 points — requires event handling and delivery logic across components. "
            "Testing and reliability concerns increase the effort."
        )

    return (
        "2 points — this looks like a small contained feature. "
        "It appears to need limited code changes and low coordination."
    )


@tool
def tech_stack_advisor(requirements: str) -> str:
    """Suggest 2-3 tools or frameworks for technical requirements."""
    text = requirements.lower()

    if "real-time" in text or "notification" in text:
        return (
            "FastAPI — lightweight Python framework with strong async support.\n"
            "Redis — good for pub/sub and fast message delivery.\n"
            "WebSockets — useful for pushing live updates to clients."
        )

    if "oauth" in text or "login" in text or "auth" in text:
        return (
            "FastAPI — clean backend framework for authentication endpoints.\n"
            "Authlib — simplifies OAuth client and provider flows.\n"
            "Redis — useful for short-lived session or token state."
        )

    return (
        "FastAPI — simple and beginner-friendly API framework.\n"
        "PostgreSQL — reliable database for application data.\n"
        "Redis — useful for caching and temporary state."
    )


@tool
def doc_summariser(text: str) -> str:
    """Summarise technical documentation into exactly 3 one-sentence bullet points."""
    prompt = f"""
Summarise the following technical documentation.

Rules:
- Return exactly 3 bullet points
- Each bullet must be one sentence
- Do not add any heading

Text:
{text}
"""
    result = llm.invoke(prompt).content.strip()
    return result


TOOLS = {
    "story_estimator": story_estimator,
    "tech_stack_advisor": tech_stack_advisor,
    "doc_summariser": doc_summariser,
}


def print_step(label: str, value: str) -> None:
    print(f"{label}: {value}")


def get_needed_tools(user_question: str) -> List[str]:
    text = user_question.lower()
    needed_tools = []

    if "summarise" in text or "summarize" in text or "doc:" in text:
        needed_tools.append("doc_summariser")

    if (
        "effort" in text
        or "estimate" in text
        or "story point" in text
        or "how much effort" in text
    ):
        needed_tools.append("story_estimator")

    if (
        "tech" in text
        or "stack" in text
        or "framework" in text
        or "tool should i use" in text
        or "what should i use" in text
    ):
        needed_tools.append("tech_stack_advisor")

    if (
        ("oauth" in text or "login" in text or "auth" in text)
        and "story_estimator" not in needed_tools
        and "tech_stack_advisor" not in needed_tools
    ):
        needed_tools.extend(["tech_stack_advisor", "story_estimator"])

    return needed_tools


def get_missing_tools(state: AgentState) -> List[str]:
    needed = get_needed_tools(state["user_question"])
    used = state["used_tools"]
    return [tool_name for tool_name in needed if tool_name not in used]


def reason_node(state: AgentState) -> AgentState:
    if state["tool_calls"] >= MAX_TOOL_CALLS:
        best_answer = make_final_answer(state)
        print_step("Thought", "I reached the 6-tool-call limit, so I will stop.")
        print_step("Final Answer", best_answer)
        return {
            **state,
            "thought": "I reached the 6-tool-call limit, so I will stop.",
            "action": "final_answer",
            "final_answer": best_answer,
        }

    missing_tools = get_missing_tools(state)

    if missing_tools:
        next_tool = missing_tools[0]
        thought = f"I still need to call {next_tool} before giving the final answer."

        print_step("Thought", thought)
        print_step("Action", next_tool)
        print_step("Action Input", state["user_question"])

        return {
            **state,
            "thought": thought,
            "action": next_tool,
            "action_input": state["user_question"],
        }

    prompt = f"""
You are a development assistant.

Available tools:
1. story_estimator -> use for effort, story points, complexity
2. tech_stack_advisor -> use for framework, tools, stack suggestions
3. doc_summariser -> use for summarising pasted documentation

Rules:
- Think step by step
- Choose only one action at a time
- If enough information is available, return final_answer
- Do not invent tool results
- If the needed tools are already used, return final_answer

User question:
{state["user_question"]}

Previous observations:
{state["observations"]}

Used tools:
{state["used_tools"]}
"""
    decision = planner.invoke(prompt)

    print_step("Thought", decision.thought)

    if decision.action == "final_answer":
        final_text = decision.final_answer or make_final_answer(state)
        print_step("Final Answer", final_text)
        return {
            **state,
            "thought": decision.thought,
            "action": "final_answer",
            "final_answer": final_text,
        }

    action_input = decision.action_input if decision.action_input else state["user_question"]

    print_step("Action", decision.action)
    print_step("Action Input", action_input)

    return {
        **state,
        "thought": decision.thought,
        "action": decision.action,
        "action_input": action_input,
    }


def tool_node(state: AgentState) -> AgentState:
    tool_name = state["action"]
    tool_input = state["action_input"]

    selected_tool = TOOLS[tool_name]
    result = selected_tool.invoke(tool_input)

    print_step("Observation", result)
    print()

    return {
        **state,
        "observation": result,
        "observations": state["observations"] + [result],
        "tool_calls": state["tool_calls"] + 1,
        "used_tools": state["used_tools"] + [tool_name],
    }


def make_final_answer(state: AgentState) -> str:
    prompt = f"""
Answer the user's original question using only the tool results below.

Rules:
- Do not invent any extra effort estimate
- If story_estimator result exists, use that exact estimate
- If tech_stack_advisor result exists, include those recommendations
- If doc_summariser result exists, return the summary clearly
- Keep the answer simple and direct

User question:
{state["user_question"]}

Tool results:
{state["observations"]}
"""
    return llm.invoke(prompt).content.strip()


def route_after_reason(state: AgentState) -> str:
    if state["action"] == "final_answer":
        return "end"
    return "tool"


graph = StateGraph(AgentState)
graph.add_node("reason", reason_node)
graph.add_node("tool", tool_node)

graph.set_entry_point("reason")
graph.add_conditional_edges(
    "reason",
    route_after_reason,
    {
        "tool": "tool",
        "end": END,
    },
)
graph.add_edge("tool", "reason")

app = graph.compile()

from IPython.display import Image, display

png_bytes = app.get_graph().draw_mermaid_png()

with open("logic.png", "wb") as f:
    f.write(png_bytes)

print("Graph image saved as langgraph.png")


def run_agent(user_question: str) -> str:
    start_state: AgentState = {
        "user_question": user_question,
        "thought": "",
        "action": "",
        "action_input": "",
        "observation": "",
        "observations": [],
        "tool_calls": 0,
        "final_answer": "",
        "used_tools": [],
    }

    result = app.invoke(start_state)
    return result["final_answer"]


if __name__ == "__main__":
    print("Development Assistant")
    print("Type 'exit' to stop\n")

    while True:
        question = input("You: ")

        if question.lower() == "exit":
            print("Goodbye!")
            break

        answer = run_agent(question)
        print(f"Assistant: {answer}\n")
