# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
import os
from typing import Any, Dict, List, Literal, TypedDict

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph


REQUIRED_PLAN_FIELDS = {
    "step_name",
    "description",
    "expected_output",
    "acceptance_criteria",
}
VALID_EFFORTS = {"small", "medium", "large"}


class AgentState(TypedDict):
    request: str
    plan: List[Dict[str, str]]
    current_step_idx: int
    execution_log: List[str]
    review: Dict[str, Any]


load_dotenv()

if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY is missing. Put it in your .env file.")

PLANNER_LLM = ChatOpenAI(model="gpt-4o-mini", temperature=0.7)
EXECUTOR_LLM = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)
REVIEWER_LLM = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)


def strip_code_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if len(lines) >= 2 and lines[-1].strip() == "```":
            return "\n".join(lines[1:-1]).strip()
    return text


def parse_json(text: str) -> Any:
    return json.loads(strip_code_fences(text))


def validate_plan(plan: Any) -> List[Dict[str, str]]:
    if not isinstance(plan, list):
        raise ValueError("Planner output must be a JSON array.")
    if not 4 <= len(plan) <= 6:
        raise ValueError("Planner must return 4 to 6 steps.")

    validated: List[Dict[str, str]] = []
    for idx, step in enumerate(plan, start=1):
        if not isinstance(step, dict):
            raise ValueError(f"Step {idx} is not a JSON object.")
        missing = REQUIRED_PLAN_FIELDS - set(step.keys())
        if missing:
            raise ValueError(f"Step {idx} is missing fields: {sorted(missing)}")
        cleaned = {key: str(step[key]).strip() for key in REQUIRED_PLAN_FIELDS}
        validated.append(cleaned)

    return validated


def validate_executor_result(result: Any) -> Dict[str, Any]:
    required = {"technical_approach", "dependencies", "effort_estimate"}
    if not isinstance(result, dict):
        raise ValueError("Executor output must be a JSON object.")
    missing = required - set(result.keys())
    if missing:
        raise ValueError(f"Executor output missing fields: {sorted(missing)}")

    effort = str(result["effort_estimate"]).strip().lower()
    if effort not in VALID_EFFORTS:
        raise ValueError("effort_estimate must be small, medium, or large.")

    dependencies = result["dependencies"]
    if isinstance(dependencies, str):
        dependencies = [dependencies]
    if not isinstance(dependencies, list):
        raise ValueError("dependencies must be a list or string.")

    return {
        "technical_approach": str(result["technical_approach"]).strip(),
        "dependencies": [str(item).strip() for item in dependencies],
        "effort_estimate": effort,
    }


def validate_review(review: Any) -> Dict[str, Any]:
    required = {"coverage_score", "gaps", "recommendation"}
    if not isinstance(review, dict):
        raise ValueError("Reviewer output must be a JSON object.")
    missing = required - set(review.keys())
    if missing:
        raise ValueError(f"Reviewer output missing fields: {sorted(missing)}")

    score = int(review["coverage_score"])
    if not 1 <= score <= 5:
        raise ValueError("coverage_score must be between 1 and 5.")

    gaps = review["gaps"]
    if isinstance(gaps, str):
        gaps = [gaps]
    if not isinstance(gaps, list):
        raise ValueError("gaps must be a list or string.")

    recommendation = str(review["recommendation"]).strip()
    return {
        "coverage_score": score,
        "gaps": [str(item).strip() for item in gaps],
        "recommendation": recommendation,
    }


def call_json_llm(
    llm: ChatOpenAI,
    system_prompt: str,
    user_prompt: str,
    validator,
) -> Any:
    response = llm.invoke(
        [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]
    )
    raw = response.content

    try:
        return validator(parse_json(raw))
    except Exception:
        correction_prompt = (
            f"{user_prompt}\n\n"
            "Your previous answer was not valid for the required JSON schema.\n"
            "Return ONLY valid JSON. No markdown, no commentary.\n"
            f"Previous output:\n{raw}"
        )
        retry = llm.invoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(content=correction_prompt),
            ]
        )
        return validator(parse_json(retry.content))


def planner_node(state: AgentState) -> AgentState:
    system_prompt = (
        "You are the Planner node in a software delivery workflow.\n"
        "Return ONLY a JSON array with 4 to 6 ordered steps.\n"
        "Each step must contain exactly these fields:\n"
        "step_name, description, expected_output, acceptance_criteria.\n"
        "Make the plan practical, logically sequenced, and delivery-focused."
    )
    user_prompt = f"Feature request: {state['request']}"

    plan = call_json_llm(PLANNER_LLM, system_prompt, user_prompt, validate_plan)

    return {
        "request": state["request"],
        "plan": plan,
        "current_step_idx": 0,
        "execution_log": state["execution_log"],
        "review": state["review"],
    }


def executor_node(state: AgentState) -> AgentState:
    idx = state["current_step_idx"]
    step = state["plan"][idx]
    total = len(state["plan"])

    system_prompt = (
        "You are the Executor node.\n"
        "You execute exactly one plan step at a time.\n"
        "Return ONLY a JSON object with these fields:\n"
        "technical_approach, dependencies, effort_estimate.\n"
        "technical_approach must be 2-3 sentences.\n"
        "effort_estimate must be one of: small, medium, large."
    )

    user_prompt = (
        f"Original request:\n{state['request']}\n\n"
        f"Full plan:\n{json.dumps(state['plan'], indent=2)}\n\n"
        f"Current step ({idx + 1}/{total}):\n{json.dumps(step, indent=2)}\n\n"
        f"Previous execution log:\n{json.dumps(state['execution_log'], indent=2)}"
    )

    result = call_json_llm(
        EXECUTOR_LLM,
        system_prompt,
        user_prompt,
        validate_executor_result,
    )

    log_entry = f"Step {idx + 1}/{total}: {json.dumps(result, ensure_ascii=False)}"
    updated_log = state["execution_log"] + [log_entry]

    return {
        "request": state["request"],
        "plan": state["plan"],
        "current_step_idx": idx + 1,
        "execution_log": updated_log,
        "review": state["review"],
    }


def reviewer_node(state: AgentState) -> AgentState:
    system_prompt = (
        "You are the Reviewer node.\n"
        "Assess whether the execution log is delivery-ready.\n"
        "Return ONLY a JSON object with exactly these fields:\n"
        "coverage_score, gaps, recommendation.\n"
        "coverage_score must be 1 to 5.\n"
        "recommendation must be either 'Approved for development' or "
        "'Needs revision: <specific changes required>'."
    )

    user_prompt = (
        f"Original request:\n{state['request']}\n\n"
        f"Execution log:\n{json.dumps(state['execution_log'], indent=2)}"
    )

    review = call_json_llm(REVIEWER_LLM, system_prompt, user_prompt, validate_review)

    return {
        "request": state["request"],
        "plan": state["plan"],
        "current_step_idx": state["current_step_idx"],
        "execution_log": state["execution_log"],
        "review": review,
    }


def route_after_executor(state: AgentState) -> Literal["executor", "reviewer"]:
    if state["current_step_idx"] < len(state["plan"]):
        return "executor"
    return "reviewer"


def build_graph():
    graph = StateGraph(AgentState)

    graph.add_node("planner", planner_node)
    graph.add_node("executor", executor_node)
    graph.add_node("reviewer", reviewer_node)

    graph.add_edge(START, "planner")
    graph.add_edge("planner", "executor")
    graph.add_conditional_edges(
        "executor",
        route_after_executor,
        {
            "executor": "executor",
            "reviewer": "reviewer",
        },
    )
    graph.add_edge("reviewer", END)

    return graph.compile()


def run_feature(app, feature_request: str) -> AgentState:
    initial_state: AgentState = {
        "request": feature_request,
        "plan": [],
        "current_step_idx": 0,
        "execution_log": [],
        "review": {},
    }

    result = app.invoke(initial_state)

    print("=" * 80)
    print(f"FEATURE: {feature_request}")
    print("=" * 80)
    print("\nPLAN JSON")
    print(json.dumps(result["plan"], indent=2))
    print("\nEXECUTION LOG")
    for item in result["execution_log"]:
        print(item)
    print("\nREVIEW")
    print(json.dumps(result["review"], indent=2))
    print()

    return result


def main():
    app = build_graph()

    # features = [
    #     "Add email notifications when a task's status changes to blocked",
    #     "Build a CSV export for the project backlog with filters by status and assignee",
    # ]

    from IPython.display import Image, display

    png_bytes = app.get_graph().draw_mermaid_png()

    with open("logic.png", "wb") as f:
        f.write(png_bytes)

    while True:
        topic = input("\nEnter topic: ").strip()

        if topic.lower() == "exit":
            print("GoodBye")
            break

        run_feature(app, topic)

    # for feature in features:
    #     run_feature(app, feature)


if __name__ == "__main__":
    main()
